[settings]

# Web interface credentials. Only HTTP Basic authentication is supported.
# If SSL or stronger auth mechanisms are required an nginx reverse proxy is recommended.
web_username = "admin"
web_password = "changeme"

# Port the service will listen for CID messages from the alarm on.
# To configure browse to the alarms report settings page: http://x.x.x.x/report.htm
# Set index 1 to this: ip://<mac_of_alarm>@<address_of_server>:8765/CID (mac_of_alarm is formatted like 001d94123456)
# NOTE: Normally this server prefers to identify alarms by MAC address but older alarms like CTC-1735 may only accept
# a 6 digit account number. In this case make up a number, configure it and set it in the account_number field (below).
cid_port = 8765

# Port the XMPP server will run on
# To configure browse to the alarms XMPP settings page: http://x.x.x.x/network.htm
# Set XMPP to xmpp://<address_of_server>:5222
# XMPP domain and buddy settings are ignored by this service. Leave them as is.
xmpp_port = 5222

# Port for the web interface presented by this project (NOT the alarm's web interface).
web_port = 8085

# Port for the HTTP polling endpoint. Only used by ancient alarms like CTC-1735 which hard code it to port 80.
# To configure browse to the "polling" screen and set the remote address to this service.
# path should be set to /polling/receivexml
# polling_port = 80

# Port for the endpoint the alarm uploads media from camera devices to.
# To configure browse to the alarm's upload settings page: http://<x.x.x.x>/upload.htm
# Set the first entry to http://<address_of_server>:8760/media/upload
# Set the "Prefix" to the MAC address of the alarm formatted like 001d94123456
media_port = 8760
# Address of SMTP server for outbound notification emails

smtp_server = "smtp.isp.com"
smtp_port = 587
smtp_use_tls = true

# Time before a ghosted HTTP polling alarm is removed from the server.
polling_timeout_minutes = 15

# Advanced logging settings
log_xmpp_streams = true
log_xml_polling = true

# Configuration block for a specific panel.
# Once the alarm connects the server will use these settings.
# If an alarm connects which isn't configured in this file sensible defaults are used instead.
# Set the MAC address suffix (001d94123456 in the below example) to the actual MAC of the alarm 

[settings.panels.001d94123456]
friendly_name = "Yale EF-IPBOX"              # Name for the alarm for use in the Web UI.
emails_from_name = "Yale Alarm"              # Name notification emails are sent from.
emails_from_address = "alarm@testdomain.com" # Address notification emails are sent from.
emails_to = "user@testdomain.com"            # Semicolon separated list of emails notifications are sent to.
media_save_path = '/path/to/media'           # Path on disk where media files are saved to. Omit this setting to skip saving to disk.
email_media = false                          # Set to true to email captured media to configured recipients.

[logging]
level = "INFO"
directory = "logs"
file_name = "alarmhomeserver.log"
max_bytes = 524288
backup_count = 5

# SSL certificate for use with SSL enabled alarms. Presently only CTC-1815.
[ssl]
cert_file = "ssl/yale-home-system-cert.pem"
key_file = "ssl/yale-home-system-key.pem"
